package net.leafenzo.lithogeology.block;


import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.leafenzo.lithogeology.ModInit;
import net.leafenzo.lithogeology.Super;
import net.leafenzo.lithogeology.item.ModItemGroups;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.leafenzo.lithogeology.ModInit;
import net.leafenzo.lithogeology.Super;
import net.leafenzo.lithogeology.item.ModItemGroups;
//import net.leafenzo.lithogeology.sound.ModBlockSoundGroup;
import net.minecraft.block.*;
import net.minecraft.entity.EntityType;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.DyeColor;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.BlockView;

public class ModBlocks {
    public static final Block BIOTITE = registerBlock("biotite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block BIOTITE_BRICKS = registerBlock("biotite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block BLOODSTONE = registerBlock("bloodstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block BLOODSTONE_BRICKS = registerBlock("bloodstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block BLUEPETRA = registerBlock("bluepetra", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block BLUEPETRA_BRICKS = registerBlock("bluepetra_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CHISELED_BIOTITE = registerBlock("chiseled_biotite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CHISELED_BLOODSTONE = registerBlock("chiseled_bloodstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CHISELED_BLUEPETRA = registerBlock("chiseled_bluepetra", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CHISELED_GELUSITE = registerBlock("chiseled_gelusite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CHISELED_JASPER = registerBlock("chiseled_jasper", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CHISELED_TURQOISE = registerBlock("chiseled_turqoise", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block COMENDITE = registerBlock("comendite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block COMENDITE_BRICKS = registerBlock("comendite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CRACKED_BIOTITE_BRICKS = registerBlock("cracked_biotite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CRACKED_BLUEPETRA_BRICKS = registerBlock("cracked_bluepetra_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block CRACKED_SHALE_TILES = registerBlock("cracked_shale_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block DEREXIUM = registerBlock("derexium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block DEREXIUM_BRICKS = registerBlock("derexium_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block DEREXIUM_TILES = registerBlock("derexium_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block FELDSPAR = registerBlock("feldspar", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block FELDSPAR_BRICKS = registerBlock("feldspar_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block GABBRO = registerBlock("gabbro", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block GABBRO_BRICKS = registerBlock("gabbro_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block GELUSITE = registerBlock("gelusite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block GELUSITE_BRICKS = registerBlock("gelusite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block GELUSITE_TILES = registerBlock("gelusite_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block HORNBLENDE = registerBlock("hornblende", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block JASPER = registerBlock("jasper", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block JASPER_BRICKS = registerBlock("jasper_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block KIMBERLITE = registerBlock("kimberlite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block KIMBERLITE_BRICKS = registerBlock("kimberlite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block MALACHITE = registerBlock("malachite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block MOSSY_BLUEPETRA_BRICKS = registerBlock("mossy_bluepetra_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block MOSSY_PERIDOTITE_BRICKS = registerBlock("mossy_peridotite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block PERIDOTITE = registerBlock("peridotite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block PERIDOTITE_BRICKS = registerBlock("peridotite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block PERIDOTITE_TILES = registerBlock("peridotite_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_BIOTITE = registerBlock("polished_biotite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_BLOODSTONE = registerBlock("polished_bloodstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_BLUEPETRA = registerBlock("polished_bluepetra", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_COMENDITE = registerBlock("polished_comendite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_DEREXIUM = registerBlock("polished_derexium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_FELDSPAR = registerBlock("polished_feldspar", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_GABBRO = registerBlock("polished_gabbro", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_GELUSITE = registerBlock("polished_gelusite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_HORNBLENDE = registerBlock("polished_hornblende", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_JASPER = registerBlock("polished_jasper", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_KIMBERLITE = registerBlock("polished_kimberlite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_PERIDOTITE = registerBlock("polished_peridotite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_PUMICE = registerBlock("polished_pumice", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_PYROXENITE = registerBlock("polished_pyroxenite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLISHED_SHALE = registerBlock("polished_shale", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block POLSIEHD_TURQOISE = registerBlock("polsiehd_turqoise", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block PUMICE = registerBlock("pumice", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block PYROXENITE = registerBlock("pyroxenite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block PYROXENITE_PILLAR = registerBlock("pyroxenite_pillar", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block SHALE_TILES = registerBlock("shale_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block SMOOTH_HORNBLENDE = registerBlock("smooth_hornblende", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block SMOOTH_PUMICE = registerBlock("smooth_pumice", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block TURQOISE = registerBlock("turqoise", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block TURQOISE_BRICKS = registerBlock("turqoise_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.IGNEOUS);
    public static final Block ANCIENT_LIMESTONE = registerBlock("ancient_limestone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CHALK = registerBlock("chalk", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CHERT = registerBlock("chert", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CHERT_BRICKS = registerBlock("chert_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CHISELED_DOLOMITE = registerBlock("chiseled_dolomite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CHISELED_IRONSTONE = registerBlock("chiseled_ironstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CHISELED_PETRAMYCES = registerBlock("chiseled_petramyces", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CONGLOMORATE = registerBlock("conglomorate", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CONGLOMORATE_BRICKS = registerBlock("conglomorate_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CRACKED_MARL_BRICKS = registerBlock("cracked_marl_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CUT_CHERT_BRICKS = registerBlock("cut_chert_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CUT_SILTSTONE_BRICKS = registerBlock("cut_siltstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CUT_SOFT_LIMESTONE = registerBlock("cut_soft_limestone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block CUT_SULFUR = registerBlock("cut_sulfur", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block DIRTY_PETRAMYCES_BRICKS = registerBlock("dirty_petramyces_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block DOLOMITE = registerBlock("dolomite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block DOLOMITE_BRICKS = registerBlock("dolomite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block FOSSIL_SOFT_LIMESTONE = registerBlock("fossil_soft_limestone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block GYPSUM = registerBlock("gypsum", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block HALITE = registerBlock("halite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block IRONSTONE = registerBlock("ironstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block IRONSTONE_BRICKS = registerBlock("ironstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block MARL_BRICKS = registerBlock("marl_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block MOSSY_MARL_BRICKS = registerBlock("mossy_marl_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block MUDSTONE = registerBlock("mudstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block MUDSTONE_BRICKS = registerBlock("mudstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block PETRAMYCES_BRICKS = registerBlock("petramyces_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_CHERT = registerBlock("polished_chert", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_CONGLOMORATE = registerBlock("polished_conglomorate", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_DOLOMITE = registerBlock("polished_dolomite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_IRONSTONE = registerBlock("polished_ironstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_IRONSTONE_BRICKS = registerBlock("polished_ironstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_MARL = registerBlock("polished_marl", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_MUDSTONE = registerBlock("polished_mudstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_PETRAMYCES = registerBlock("polished_petramyces", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_SILTSTONE = registerBlock("polished_siltstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block POLISHED_SULFUR = registerBlock("polished_sulfur", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block ROUGH_PETRAMYCES_BRICKS = registerBlock("rough_petramyces_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SEA_HALITE = registerBlock("sea_halite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SHALE = registerBlock("shale", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SILTSTONE = registerBlock("siltstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SILTSTONE_BRICKS = registerBlock("siltstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SMOOTH_PETRAMYCES = registerBlock("smooth_petramyces", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SOFT_LIMESTONE = registerBlock("soft_limestone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SULFUR = registerBlock("sulfur", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block SULFUR_PILLAR = registerBlock("sulfur_pillar", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.SEDIMENTARY);
    public static final Block AMPHIBITE = registerBlock("amphibite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block ANCIENT_LIMESTONE_BRICKS = registerBlock("ancient_limestone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block AZURITE = registerBlock("azurite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block AZURITE_TILES = registerBlock("azurite_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CHISELED_PHYLLITE = registerBlock("chiseled_phyllite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CHISELED_QUARTZITE = registerBlock("chiseled_quartzite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CHISELED_SERPENTINE = registerBlock("chiseled_serpentine", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CHISELED_WYRMITE = registerBlock("chiseled_wyrmite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block COLUBRITE = registerBlock("colubrite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block COLUBRITE_BRICKS = registerBlock("colubrite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CORUNDUM = registerBlock("corundum", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CORUNDUM_TILES = registerBlock("corundum_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_COLUBRITE_BRICKS = registerBlock("cracked_colubrite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_KYANITE_BRICKS = registerBlock("cracked_kyanite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_MARBLE_BRICKS = registerBlock("cracked_marble_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_PHYLLITE_BRICKS = registerBlock("cracked_phyllite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_SCHIST_BRICKS = registerBlock("cracked_schist_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_SLATE_BRICKS = registerBlock("cracked_slate_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_SLATE_TILES = registerBlock("cracked_slate_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CRACKED_WYRMITE_BRICKS = registerBlock("cracked_wyrmite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CUT_FUNDITUM = registerBlock("cut_funditum", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CUT_MARBLE = registerBlock("cut_marble", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CUT_STAUROLITE = registerBlock("cut_staurolite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block EMERALD_EMBEDDED_MARBLE = registerBlock("emerald_embedded_marble", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block EMERALD_EMBEDDED_SLATE = registerBlock("emerald_embedded_slate", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block FUNDITUM = registerBlock("funditum", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block GILDED_MARBLE = registerBlock("gilded_marble", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block GILDED_MARBLE_BRICKS = registerBlock("gilded_marble_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block GNIESS = registerBlock("gniess", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block GNIESS_BRICKS = registerBlock("gniess_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block GNIESS_PILLAR = registerBlock("gniess_pillar", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block HORNFELS = registerBlock("hornfels", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block HORNFELS_TILES = registerBlock("hornfels_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block JADEITE = registerBlock("jadeite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block JADEITE_BRICKS = registerBlock("jadeite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block KYANITE = registerBlock("kyanite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block KYANITE_BRICKS = registerBlock("kyanite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block MARBLE = registerBlock("marble", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block MARBLE_BRICKS = registerBlock("marble_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block MARBLE_PILLAR = registerBlock("marble_pillar", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block MARL = registerBlock("marl", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block MOSSY_MARBLE_BRICKS = registerBlock("mossy_marble_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block PETRAMYCES = registerBlock("petramyces", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block PHYLITE_QUARTZ_ORE = registerBlock("phylite_quartz_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block PHYLLITE = registerBlock("phyllite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block PHYLLITE_BRICKS = registerBlock("phyllite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_AMPHIBITE = registerBlock("polished_amphibite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_ANCIENT_LIMESTONE = registerBlock("polished_ancient_limestone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_AZURITE = registerBlock("polished_azurite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_COLUBRITE = registerBlock("polished_colubrite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_CORUNDUM = registerBlock("polished_corundum", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_FUNDITUM = registerBlock("polished_funditum", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_GNIESS = registerBlock("polished_gniess", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_HORNFELS = registerBlock("polished_hornfels", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_JADEITE = registerBlock("polished_jadeite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_KYANITE = registerBlock("polished_kyanite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_MARBLE = registerBlock("polished_marble", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_PHYLLITE = registerBlock("polished_phyllite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_QUARTZITE = registerBlock("polished_quartzite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_SCHIST = registerBlock("polished_schist", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_SERPENTINE = registerBlock("polished_serpentine", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_SKARN = registerBlock("polished_skarn", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_SLATE = registerBlock("polished_slate", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_STAUROLITE = registerBlock("polished_staurolite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block POLISHED_WYRMITE = registerBlock("polished_wyrmite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block PSEUDOCROCIDOLITE = registerBlock("pseudocrocidolite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block QUARTZITE_BRICKS = registerBlock("quartzite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SCHIST = registerBlock("schist", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SCHIST_BRICKS = registerBlock("schist_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SCHIST_TILES = registerBlock("schist_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SERPENTINE = registerBlock("serpentine", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SERPENTINE_BRICKS = registerBlock("serpentine_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SERPENTINE_TILES = registerBlock("serpentine_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SKARN = registerBlock("skarn", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SKARN_BRICKS = registerBlock("skarn_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SLATE = registerBlock("slate", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SLATE_BRICKS = registerBlock("slate_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block SLATE_TILES = registerBlock("slate_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block STAUROLITE = registerBlock("staurolite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block TIGERS_EYE = registerBlock("tigers_eye", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block WYRMITE = registerBlock("wyrmite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block WYRMITE_BRICKS = registerBlock("wyrmite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.METAMORPHIC);
    public static final Block CINNIBAR_REDSTONE_ORE = registerBlock("cinnibar_redstone_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block COLUBRITE_GOLD_ORE = registerBlock("colubrite_gold_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block DIAMOND_EMBEDDED_KIMBERLITE = registerBlock("diamond_embedded_kimberlite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block HEMATITE = registerBlock("hematite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block HEMATITE_BRICKS = registerBlock("hematite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block HEMATITE_TILES = registerBlock("hematite_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block KIMBERLITE_DIAMOND_ORE = registerBlock("kimberlite_diamond_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block LARGE_GOLD_NUGGET = registerBlock("large_gold_nugget", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block MALACHITE_BRICKS = registerBlock("malachite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block MARBLE_EMERALD_ORE = registerBlock("marble_emerald_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block POLISHED_HEMATITE = registerBlock("polished_hematite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block POLISHED_MALACHITE = registerBlock("polished_malachite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block QUARTZITE_GOLD_ORE = registerBlock("quartzite_gold_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block RAW_COAL = registerBlock("raw_coal", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block RED_SANDSTONE_GOLD_ORE = registerBlock("red_sandstone_gold_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block SANDSTONE_LAPIS_ORE = registerBlock("sandstone_lapis_ore", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.RESOURCE);
    public static final Block AGED_PLASTER = registerBlock("aged_plaster", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block BLACK_PLASTER = registerBlock("black_plaster", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block CALC = registerBlock("calc", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block CEMENT = registerBlock("cement", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block GRAY_PLASTER = registerBlock("gray_plaster", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block LIGHT_GRAY_PLASTER = registerBlock("light_gray_plaster", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block PLASTER = registerBlock("plaster", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block POLISHED_CEMENT = registerBlock("polished_cement", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block WET_CALC = registerBlock("wet_calc", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block WHITE_PLASTER = registerBlock("white_plaster", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.ANTHROPIC);
    public static final Block COBALT_METEORITE = registerBlock("cobalt_meteorite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.TEKTITE);
    public static final Block IRON_METEORITE = registerBlock("iron_meteorite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.TEKTITE);
    public static final Block SUEVITE = registerBlock("suevite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.TEKTITE);
    public static final Block ZINC_METEORITE = registerBlock("zinc_meteorite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.TEKTITE);
    public static final Block BRIMOTHE = registerBlock("brimothe", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block BRIMOTHE_BRICKS = registerBlock("brimothe_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block CHISELED_CORPUSCLIUM = registerBlock("chiseled_corpusclium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block CHISELED_SUNROCK = registerBlock("chiseled_sunrock", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block CORPUSCLIUM = registerBlock("corpusclium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block CORPUSCLIUM_BRICKS = registerBlock("corpusclium_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block DUSKSTONE = registerBlock("duskstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block DUSKSTONE_BRICKS = registerBlock("duskstone_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block GASHSTONE = registerBlock("gashstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block GASHSTONE_TILES = registerBlock("gashstone_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block POLISHED_BRIMOTHE = registerBlock("polished_brimothe", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block POLISHED_CORPUSCLIUM = registerBlock("polished_corpusclium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block POLISHED_DUSKSTONE = registerBlock("polished_duskstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block POLISHED_GASHSTONE = registerBlock("polished_gashstone", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block POLISHED_SCOPETRA = registerBlock("polished_scopetra", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block POLISHED_SUNROCK = registerBlock("polished_sunrock", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block SCOPETRA = registerBlock("scopetra", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block SCOPETRA_BRICKS = registerBlock("scopetra_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block SUNROCK = registerBlock("sunrock", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block SUNROCK_BRICKS = registerBlock("sunrock_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.NETHER);
    public static final Block CHISELED_MOONROCK = registerBlock("chiseled_moonrock", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block CHISELED_SALEROSE = registerBlock("chiseled_salerose", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block KITSUNITE = registerBlock("kitsunite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block KITSUNITE_TILES = registerBlock("kitsunite_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block MOONROCK = registerBlock("moonrock", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block MOONROCK_BRICKS = registerBlock("moonrock_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block PETRIFIED_CHORUS_BRICKS = registerBlock("petrified_chorus_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block PETRIFIED_CHOURUS = registerBlock("petrified_chourus", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block PHOBOSIUM = registerBlock("phobosium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block PHOBOSIUM_BRICKS = registerBlock("phobosium_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block POLISHED_KITSUNITE = registerBlock("polished_kitsunite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block POLISHED_MOONROCK = registerBlock("polished_moonrock", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block POLISHED_PETRIFIED_CHORUS = registerBlock("polished_petrified_chorus", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block POLISHED_PHOBOSIUM = registerBlock("polished_phobosium", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block POLISHED_SALEROSE = registerBlock("polished_salerose", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block POLISHED_VESPERITE = registerBlock("polished_vesperite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block SALEROSE = registerBlock("salerose", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block SALEROSE_BRICKS = registerBlock("salerose_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block VESPERITE = registerBlock("vesperite", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block VESPERITE_BRICKS = registerBlock("vesperite_bricks", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);
    public static final Block VESPERITE_TILES = registerBlock("vesperite_tiles", new Block(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE)), ModItemGroups.END);


    public static Block registerBlock(String name, Block block, ItemGroup group) {
        registerBlockItem(name,block,group);
        //if(block.getDefaultState().isOpaque()) { ModRenderLayers.registerCutout(block);  }
        return Registry.register(Registries.BLOCK, new Identifier(Super.MOD_ID, name), block);
    }

    private static boolean never(BlockState blockState, BlockView blockView, BlockPos blockPos) {
        return false;
    }

    public static boolean never(BlockState state, BlockView world, BlockPos pos, EntityType<?> type) {
        return false;
    }

    private static Item registerBlockItem(String name, Block block, ItemGroup group) {
        BlockItem blockItem = new BlockItem(block, new FabricItemSettings());
        ItemGroupEvents.modifyEntriesEvent(group).register(entries -> entries.add(blockItem));
        return Registry.register(Registries.ITEM, new Identifier(Super.MOD_ID, name), blockItem);
    }

    public static void registerModBlocks() {
        ModInit.LOGGER.debug("Registering mod blocks for " + Super.MOD_ID);
    }
}
